---
title: "ACM_3_main"
output: html_document
date: "2024-02-22"
---

# Setup
```{r}
pacman::p_load(tidyverse, cmdstanr, brms, gridExtra, furrr)
```

# Simulate data

```{r}
# alien features (six features) (color, arms, eyes, dots, legs)
n <- 100

creature_data <- tibble(
  color = sample(c(0, 1), n, replace = TRUE),
  legs = sample(c(0, 1), n, replace = TRUE),
  eyes = sample(c(0, 1), n, replace = TRUE),
  dots = sample(c(0, 1), n, replace = TRUE),
  arms = sample(c(0, 1), n, replace = TRUE)
)

creature_data <- creature_data %>%
    mutate(category = ifelse(eyes == 1 & dots == 1, 1, 0))# 1 = danger, 0 = friendly

creature_data
```

# agent modelling
```{r}
# Weights
weights <- c(0.5, 0.2, 0.3, 0.4, 0.5)

# scaling parameter (vector of potential c-calues): tells how much similarty decayes with distance
c = c(0.1)

# distance function
distance <- function(vect1, vect2, w) {
    return(sum(w * abs(vect1 - vect2)))
}


# similarity function
similarity <- function(distance, c) {
    return(exp(-c * distance))
}

### generative model ###
gcm <- function(w, c, obs, cat_one, quiet = TRUE) {
  # variables description
  # w: weights
  # c: scaling parameter
  # obs: observed data
  # cat_one: category of each observation

  # create an empty list to save probability of saying "1" for each trial
  r <- c()
  
  ntrials <- nrow(obs)
  
  for (i in 1:ntrials) {
    # If quiet is FALSE, print every ten trials
    if (!quiet && i %% 10 == 0) {
      print(paste("i =", i))
    }
    # if this is the first trial, or there any category with no exemplars seen yet, set the choice to random
    if (i == 1 || sum(cat_one[1:(i - 1)]) == 0 || sum(cat_one[1:(i - 1)]) == (i - 1)) {
      r <- c(r, .5)
    } else {
      similarities <- c()
      # for each previously seen stimulus assess distance and similarity
      for (e in 1:(i - 1)) {
        sim <- similarity(distance(obs[i, ], obs[e, ], w), c)
        similarities <- c(similarities, sim)
      }
      # Calculate prob of saying "1" by dividing similarity to 1 by the sum of similarity to 1 and to 2
      numerator <- 0.5 * sum(similarities[cat_one[1:(i - 1)] == 1])
      denominator <- 0.5 * sum(similarities[cat_one[1:(i - 1)] == 1]) + 0.5 * sum(similarities[cat_one[1:(i - 1)] == 0])
      r <- c(r, numerator / denominator)
    }
  }

  return(rbinom(ntrials, 1, r))
}

```


```{r}

# Simulate choices function
simulate_responses <- function(agent, w, c) {
    
    observations <- creature_data # EOL: experiment should be our stimuli data (we should take creature data)

    
    category <- creature_data$category
    
    if (w == "equal") {
        weight <- rep(1 / 5, 5) # equally skewed
    } else if (w == "skewed1") { # a little but skewed
        weight <- c(0.1, 0.1,0.1,0.3,0.4)
    } else if (w == "skewed2") { # extremely skewed
        weight <- c(0.0, 0.0, 0.0, 0.0, 1)
    }

    # simulate responses
    responses <- gcm(
        weight,
        c,
        observations,
        category
    )
    
    tmp_simulated_responses <- creature_data %>%
        mutate(
            trial = seq(nrow(creature_data)),
            sim_response = responses,
            correct = ifelse(category == sim_response, 1, 0),
            performance = cumsum(correct) / seq_along(correct),
            c = c,
            w = w,
            agent = agent
        )

    return(tmp_simulated_responses)
}

# actually simulate the data
# simulate responses
plan(multisession, workers = availableCores())

param_df <- dplyr::tibble(
    expand_grid(
        agent = 1:10,
        c = seq(.1, 10, 1), # 0.1 to 6 with 0.2 increments 
        w = c("equal", "skewed1", "skewed2")
    )
)

simulated_responses <- future_pmap_dfr(param_df,
    simulate_responses,
    .options = furrr_options(seed = TRUE)
)

```

```{r}
simulated_responses
```

Plotting
```{r}
p3 <- simulated_responses %>%
  mutate(w = as.factor(w)) %>%
  ggplot(aes(trial, performance, group = w, color = w)) +
  geom_smooth() +
  theme_bw() +
  facet_wrap(c ~ .)

# # save to drive
ggsave("p3.png", p3, width = 10, height = 10)

p4 <- simulated_responses %>%
  mutate(c = as.factor(c)) %>%
  ggplot(aes(trial, performance, group = c, color = c)) +
  geom_smooth() +
  theme_bw() +
  facet_wrap(w ~ .)

grid.arrange(p3, p4, ncol = 1)
```

Compiling stan model
```{r}
file <- file.path("stan_model/GCM.stan")

GCM_mod <- cmdstan_model(file, cpp_options = list(stan_threads = TRUE), stanc_options = list("O1"), pedantic = TRUE)
```

```{r}
simulated_responses
```

```{r}
head(creature_data,1)
```

Fitting the model to simulated data
```{r}
d <- simulated_responses %>% subset(
  c == "7.1" & w == "equal"
)

gcm_data <- list(
  ntrials = nrow(d),
  nfeatures = 5,
  cat_one = d$category,
  y = d$sim_response,
  obs = as.matrix(d[, c("color",  "legs",  "eyes",  "dots",  "arms")]),
  b = 0.5,
  w_prior_values = c(1,1,1,1,1),
  c_prior_values = c(0, 1) # 0 = mean, 1 = variance
)

samples_gcm <- GCM_mod$sample(
  data = gcm_data,
  seed = 123,
  chains = 1,
  parallel_chains = 1,
  threads_per_chain = 4,
  iter_warmup = 1000,
  iter_sampling = 1000,
  refresh = 500
)
```

# assessing model
```{r}
# diagnosing the mdoel
samples_gcm$cmdstan_diagnose()
```

# summary
```{r}
# sumarizing model
samples_gcm$summary()
```

# draws DF trace Plotting
```{r}
draws_df <- as_draws_df(samples_gcm$draws())

ggplot(draws_df, aes(.iteration, c, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
```


# on real data
```{r}
# load data
data <- read.csv("data/AlienData.txt")

# remove all rows where stimuli contains "pt"
data <- data %>% filter(!grepl("pt", stimulus))

# filter so that if response is 3 or 4, test is 1, otherwise 2 REMEMBER TO CHANGE THIS ACCORDING TO THE CORRECT SYSTEM
data$test <- ifelse(data$response == 3 | data$response == 4, 1, 2)

# subsetting data for subject one in session 1
d_ses1_sub1 <- data %>% subset(
  session == 1 & subject == 1
)
```

fitting on real data
```{r}
gcm_data_real <- list(
  ntrials = nrow(d_ses1_sub1),
  nfeatures = 5,
  cat_one = d_ses1_sub1$category,
  y = d_ses1_sub1$response,
  obs = as.matrix(d[, c("color",  "legs",  "eyes",  "dots",  "arms")]),
  b = 0.5,
  w_prior_values = c(1,1,1,1,1),
  c_prior_values = c(0, 1) # 0 = mean, 1 = variance
)
```
